application: goog-stack
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /client/app
  static_dir: client/app

- url: /client/vendor
  static_dir: client/vendor

- url: /client/.*
  static_files: client/index.html
  upload: client/index\.html

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /api/records/.*  # TODO: Make api.py?
  script: server.record.handler.app  # TODO: Better naming convention?  handler is weird?

- url: .*
  script: server.main.app

libraries:
- name: webapp2
  version: "2.5.2"
